# BlackReign Command Center Configuration

# Network settings
listen_address: "0.0.0.0"
listen_port: 8443
use_ssl: true

# Operation settings
heartbeat_interval: 60  # seconds
max_retry_attempts: 5
command_timeout: 120    # seconds
operation_timeout: 3600 # seconds (1 hour)
max_concurrent_tasks: 10

# Encryption settings
encryption:
  asymmetric: "RSA"
  symmetric: "AES"
  key_size: 3072
  key_rotation_interval: 604800  # seconds (7 days)

# Logging settings
log_level: "INFO"
log_file: "blackreign.log"
log_max_size: 10485760  # bytes (10 MB)
log_backup_count: 5

# Command and Control settings
c2_channels:
  - type: "http"
    enabled: true
    endpoint: "/api/data"
    port: 8443
    jitter: 30      # percent
    interval: 60    # seconds
    timeout: 30     # seconds
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  
  - type: "dns"
    enabled: false
    domain: "example.com"
    record_type: "TXT"
    jitter: 20      # percent
    interval: 300   # seconds
    timeout: 60     # seconds

# Strategy settings
strategies:
  aggressive:
    priority: 10
    conditions:
      detection_risk: "low"
      target_value: "high"
    
  stealthy:
    priority: 20
    conditions:
      detection_risk: "high"
      
  maintenance:
    priority: 5
    conditions:
      uptime: 
        __operator__: "gt"
        value: 86400  # seconds (24 hours)

# Alert thresholds
alerts:
  implant_offline: 300  # seconds
  high_traffic: 1000    # requests per minute
  suspicious_activity: 5  # score threshold